# Generated by Django 5.2.13 on 2026-06-13 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RSVPImportConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_columns', models.JSONField(blank=True, default=list)),
                ('display_columns', models.JSONField(blank=True, default=list)),
                ('searchable_columns', models.JSONField(blank=True, default=list)),
                ('unique_identifier_strategy', models.CharField(choices=[('column', 'Column'), ('name_timestamp', 'Name + Timestamp'), ('internal', 'Generate Internal RSVP ID')], default='column', max_length=32)),
                ('unique_identifier_source', models.CharField(blank=True, max_length=255)),
                ('name_column', models.CharField(blank=True, max_length=255)),
                ('major_column', models.CharField(blank=True, max_length=255)),
                ('email_column', models.CharField(blank=True, max_length=255)),
                ('timestamp_column', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'RSVP import configuration',
                'verbose_name_plural': 'RSVP import configurations',
            },
        ),
        migrations.AddField(
            model_name='registeredparticipant',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='registeredparticipant',
            name='major',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='registeredparticipant',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='registeredparticipant',
            name='unid',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
